### ISSUE TITLE
Literature Review: MESA

### ISSUE THREAD

**Issue by clorton** [InstituteforDiseaseModeling/laser#2]
https://mesa.readthedocs.io/

"Create an agent based SEIR disease model with 1 million agents distributed unevenly across 25 nodes with an initial outbreak of 100 agents. &beta; and mean incubation period are inputs to the model. Run for 1 simulated year and plot the aggregated SEIR curves for the total population and the SEIR curves for each node in a 5 by 5 grid of plots."

**Comment by krosenfeld-IDM** [comment]
The link appears broken @clorton

**Comment by clorton** [comment]
Fixed.

**Comment by jonathanhhb** [comment]
Self-assigned since I've already invested a couple of hours on this one.

**Comment by jonathanhhb** [comment]
"Its goal is to be the Python-based counterpart to NetLogo, Repast, or MASON."

**Comment by jonathanhhb** [comment]
```
I need an agent-based modeling framework that can run spatially and can run on GPU.

ChatGPT
One powerful agent-based modeling (ABM) framework that supports spatial modeling and GPU acceleration is Mesa.
````
