### ISSUE TITLE
Literature Review: Agents.jl

### ISSUE THREAD

**Issue by clorton** [InstituteforDiseaseModeling/laser#3]
https://github.com/JuliaDynamics/Agents.jl/

"Create an agent based SEIR disease model with 1 million agents distributed unevenly across 25 nodes with an initial outbreak of 100 agents. &beta; and mean incubation period are inputs to the model. Run for 1 simulated year and plot the aggregated SEIR curves for the total population and the SEIR curves for each node in a 5 by 5 grid of plots."

**Comment by krosenfeld-IDM** [comment]
See InstituteforDiseaseModeling/abm-software-comparison@895f4d0
