### ISSUE TITLE
Age targeting with SIAs

### ISSUE THREAD

**Issue by krosenfeld-IDM** [InstituteforDiseaseModeling/laser#30]
On commit [9a1ba81](https://github.com/InstituteforDiseaseModeling/laser/commit/9a1ba81ae2371cc7f7d71f9716a416c239941621)
 · SIAs are not age targeted. A good range is 9months to 5 years, single day but should be flexible with regard to age range.

**Comment by clorton** [comment]
Minor questions @krosenfeld-IDM :
1) How many days is 9 months in an idealized 365 day year? 270? 274?
2) Does 9 months - 5 years include or exclude 5.0 - 5.997 year olds?

**Comment by clorton** [comment]
Fixed with commit e6b0005.

Checked in code uses [2,5) years but is easily modified for 9 mos. - 5.x years. Subsequent commits will default to [9 months, 6 years).

**Comment by krosenfeld-IDM** [comment]
Thanks @clorton . My suggestion is to use 273 days to 1825 days.

https://github.com/krosenfeld-IDM/hmer-measles-elimination-landscape/blob/2a234c835e74caa1739405da5dc72eda7b93cec8/model_measles_nga04/Assets/data/NGA_MCV_SIA.json#L65-L66
