### ISSUE TITLE
Random seed

### ISSUE THREAD

**Issue by krosenfeld-IDM** [InstituteforDiseaseModeling/laser#31]
From [9a1ba81](https://github.com/InstituteforDiseaseModeling/laser/commit/9a1ba81ae2371cc7f7d71f9716a416c239941621) it would be helpful to set a random seed to ensure replicability / reproducibility

**Comment by clorton** [comment]
Fixed in FUSION with 7234c55.

**Comment by clorton** [comment]
Verified that I get same results on a different machine with different CPU architecture (x64 vs. Apple M1) as long as I use `nb.set_num_threads()` to make sure the simulation is using the same number of threads.

**Comment by krosenfeld-IDM** [comment]
@clorton - thanks for taking a look at this and checking that your solution works on a different CPU architecture. I was curious whether just using a `seed` function failed:

```
@nb.njit(parallel=True)
def seed(a):
    for i in nb.prange(nb.get_num_threads()):
        random.seed(a+i)


@nb.njit(
    (nb.float64[:],),
    parallel=True,
    nogil=True,
    cache=True,
)
def fill_me(arr):
    for i in nb.prange(len(arr)):
        arr[i] = random.normalvariate(mu=0, sigma=1)
    return
```

**Comment by krosenfeld-IDM** [comment]
It's really hard to see what the solution was in the `diff` for the .ipynb.

**Comment by krosenfeld-IDM** [comment]
Hmm - I guess the issue becomes if you want to be using the `numpy.random` distributions then you won't be using the `random.random` generator.

**Comment by krosenfeld-IDM** [comment]
It looks like maybe the `prng` still needs to be incorporated into the transmission loop?

https://github.com/InstituteforDiseaseModeling/laser/blob/2ce4764876daa91d69b2212c02d1bec3b5b8ec7e/nnmm/measles.py#L753

**Comment by clorton** [comment]
- [ ] do `np.random` functions use the same PRNG as `np.random.default_rng()`?
- [ ] do subsequent calls to `np.random.default_rng()` get the _same_ PRNG or just the same algorithm?
- [ ] if Numba's threads are seeded once, do all subsequent Numba-fied functions use the same PRNG?

**Comment by clorton** [comment]
- do `np.random` functions use the same PRNG as `np.random.default_rng()` - **No** `np.random.default_rng()` [Construct a new Generator with the default BitGenerator (PCG64).](https://numpy.org/doc/stable/reference/random/generator.html)
- do subsequent calls to `np.random.default_rng()` get the _same_ PRNG or just the same algorithm? - **Same algorithm** (see above)
- if Numba's threads are seeded once, do all subsequent Numba-fied functions use the same PRNG? - **Yes** but the non-parallel generator is separate from the per-thread generators.
