### ISSUE TITLE
Literature Review: epydemic

### ISSUE THREAD

**Issue by clorton** [InstituteforDiseaseModeling/laser#6]
https://pyepydemic.readthedocs.io/en/latest/

"Create an agent based SEIR disease model with 1 million agents distributed unevenly across 25 nodes with an initial outbreak of 100 agents. &beta; and mean incubation period are inputs to the model. Run for 1 simulated year and plot the aggregated SEIR curves for the total population and the SEIR curves for each node in a 5 by 5 grid of plots."

**Comment by jonathanhhb** [comment]
Deemed not worth deeper investigation by @KevinMcCarthyAtIDM 

"Person-to-person transmission-network, no spatial metapopulations"
