### ISSUE TITLE
Literature Review: MASON

### ISSUE THREAD

**Issue by clorton** [InstituteforDiseaseModeling/laser#7]
https://cs.gmu.edu/~eclab/projects/mason/

"Create an agent based SEIR disease model with 1 million agents distributed unevenly across 25 nodes with an initial outbreak of 100 agents. &beta; and mean incubation period are inputs to the model. Run for 1 simulated year and plot the aggregated SEIR curves for the total population and the SEIR curves for each node in a 5 by 5 grid of plots."

**Comment by jonathanhhb** [comment]
"MASON 21 is a fast agent-based simulation library core in Java, designed to be the foundation for large custom-purpose Java simulations, and also to provide more than enough functionality for many lightweight simulation needs. MASON contains both a model library and an optional suite of visualization tools in 2D and 3D."

There is now a Distributed MASON (presumably to run at scale) and GeoMASON, with GIS integration.

There is also reportedly a 450 page documentation manual.

**Comment by jonathanhhb** [comment]
Seems to have a lot going for it but the ubiquitous Java thing seems like it would be a pretty serious tech change for us.
