### ISSUE TITLE
Literature Review: NetLogo

### ISSUE THREAD

**Issue by clorton** [InstituteforDiseaseModeling/laser#8]
http://ccl.northwestern.edu/netlogo/

"Create an agent based SEIR disease model with 1 million agents distributed unevenly across 25 nodes with an initial outbreak of 100 agents. &beta; and mean incubation period are inputs to the model. Run for 1 simulated year and plot the aggregated SEIR curves for the total population and the SEIR curves for each node in a 5 by 5 grid of plots."

**Comment by jonathanhhb** [comment]
Found a nation-scale disease transmission project done with NetLogo: https://www.youtube.com/watch?v=wAhSOfNQ_B4
**How big was the model in terms of agents?**
The model had a scaled population of just under five million people, with one agent representing 100 similar people in the real Ireland.
**How long did it take the model to run?**
It took about a day to run the full set of runs on a computer or a couple hours on an HPC cluster.
It depends on the specific model being run, but on average, it took about a day to run the full set of runs on a laptop or desktop computer. However, if the model was run on a high-performance computing cluster, it only took a couple of hours.
**So each individual run of a full-scale model (5 million people or 50,000 agents) took 2 hours on the cluster?**
 Yes, that is correct. Each individual run of the full-scale model took approximately 2 hours on the cluster.
**Was the NetLogo software easy to work with?**
 Yes, the speaker mentions that they were able to create a rich and complex model using NetLogo and were able to run it efficiently on different types of computers. They also mention that there are tutorials available on the NetLogo website, which suggests that the software is user-friendly and easy to learn.
