### ISSUE TITLE
check action failing

### ISSUE THREAD

**Issue by krosenfeld-IDM** [InstituteforDiseaseModeling/laser#90]
I am continuing to bump into failure at `check` with the error tracing down to :

```
@krosenfeld-IDM ➜ /workspaces/laser-cohorts (separate-doc-build) $ python setup.py check --strict --metadata --restructuredtext
running check
warning: check: Possible title underline, too short for the title.
Treating it as ordinary text because it's so short. (line 8)

error: Please correct your package.
```

This is very difficult to figure out what the problem is. I have checked for issues with section titles in my 
- README.rst
- CHANGELOG.rst

**Comment by clorton** [comment]
Try changing each of the triple tick "```" blocks in README.md to specify one of the following: shell, sh, zsh, bash

E.g.,
\`\`\`shell
somecommand -h
\`\`\`

```shell
somecommand -h
```
Triple ticks from Markdown seem to confuse the rST checker (note the `--restructuredtext` option to `setup.py check`).

**Comment by krosenfeld-IDM** [comment]
thanks.
